name : Laravel & PostgreSQL 

on : 
   push : 
     branches : [main] 
  pull_request : 
     branches : [main] 

jobs : 
   container-job : 
     runs-on : ubuntu-18.04 

    # all steps within the specified continental rather than on the VM host. 
    container : 
       image : php: 8.1-alpine 

    services : 
       postgres : 
         image : mdillon / postgis: 10 
        env : 
           POSTGRES_DB : postgresdb 
          POSTGRES_USER : postgresuser 
          POSTGRES_PASSWORD : secret 
          POSTGRES_HOST : postgres 
        ports : 
         : 5432 
        #postgres container does not provide healthcheck and is required. 
        options : --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 

    steps : 
     --uses env : actions / checkout @ 
      v1 : 
         # Here we are specifying a container for the job, so we will use postgres for the host 
        # If we run the job on a VM, it will be localhost. 
        POSTGRES_HOST : postgres 
        POSTGRES_PORT : $ {{job.services.postgres.ports [5432]}} 

  # Perform all steps on the VM 
  #The service container uses the host port binding instead of the container network, so in the service name Access on the local host instead. 
  vm-job : 
     runs-on : ubuntu-18.04 
    services : 
       postgres : 
         image : postgres: 14 
        env : 
           POSTGRES_DB : postgresdb 
          POSTGRES_USER : postgresuser 
          POSTGRES_PASSWORD : secret 
          POSTGRES_HOST : postgres 
        ports : 
         --The 5432 / tcp 
        # postgres container does not provide a healthcheck and is required. 
        options : --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 
    
    steps : 
     --uses v1 : actions / checkout @ 
     : uses actions Use Node.js 12.x 
      : : node @ v1 
      with - 
         node-version : 12.x 

     - --prefer : Install composer dependencies 
      run : dist 

     : --name : Install npm dependencies 
      run npm ci 
    
     : --name : Run Mix 
      run npm run production 
      
     coverage - : Run PHPUnit tests 
      run : vendor / bin / phpunit --no 
      env : 
         # Here we are specifying a container for the job, so we will use localhost for the host. 
        # When running a job on a VM, it will be postgres. 
        DB_HOST : localhost 
        DB_PORT : $ {{job.services.postgres.ports [5432]}} # Get randomly assigned public ports 
